#!/bin/bash

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`

function mysed() {
		replace="$1"
		iNew="$itext"
		iNew=$(echo "$itext" | sed "$replace")
		if [ ! "$iNew" = "$itext" ]; then
			itext="$iNew"
		else
			echo "----------------------------------------"
			echo "Nicht ersetzt:"
			echo "SED-Befehl: $replace"
			echo "Datei: $i"
			echo "----------------------------------------"
		fi
}

function replaceValuesInFile () {
	i=$1
	echo "Datei: $i"
	if [ -f "$i" ]; then
		#set -x

		# Eigene Language Dateien unver\&auml;ndert belassen
		if [[ ! "$i" = *germanFiles* ]]; then

			itext=`cat "$i"`

			if [[ "$i" = */help.php ]]; then
				mysed 's/>Help center</>Hilfe</g'
				mysed 's/>Header</>Kopfzeile</g'
				mysed 's/>Top left: Status display</>Oben links: Statusanzeige</g'
				mysed 's/>Shows different status messages:</>Zeigt verschiede Statusmeldungen an (Diese Meldungen werden nicht regelm\&auml;\&szlig;ig aktualisiert!):</g'
				mysed 's/>Status: Current status of the Pi-hole - Active (<i class="fa fa-circle" style="color:#7FFF00"><\/i>), Offline (<i class="fa fa-circle" style="color:#FF0000"><\/i>), or Starting (/>Status: Aktiver Status vom Pi-Hole - Aktiv (<i class="fa fa-circle" style="color:#7FFF00"><\/i>), Offline (<i class="fa fa-circle" style="color:#FF0000"><\/i>), oder Startend (/g'
				mysed 's/>Temp: Current CPU temperature</>Temp: Aktuelle CPU Temperatur</g'
				mysed 's/>Load: load averages for the last minute, 5 minutes and 15 minutes, respectively. A load average of 1 reflects the full workload of a single processor on the system. We show a red icon if the current load exceeds the number of available processors on this machine (which is <?php echo $nproc; ?>)</>Auslst.: Auslastungs Durchschnittswerte für die letzte Minute, 5 Minuten bzw. 15 Minuten. Ein Lastdurchschnitt von 1 git die volle Auslastung eines einzelnen Prozessors im System an. Wir zeigen ein rotes Symbol an, wenn die aktuelle Last die Anzahl der verf\&uuml;gbaren Prozessoren auf diesem Computer \&uuml;berschreitet (aktuell: <?php echo $nproc; ?> Prozessor(en))</g'
				mysed 's/>Memory usage: Shows the percentage of memory actually blocked by applications. We show a red icon if the memory usage exceeds 75%</>Speichernutzung: Zeigt den Prozentsatz des Speichers an, der tats\&auml;chlich von Anwendungen blockiert wurde. Wir zeigen ein rotes Symbol, wenn die Speichernutzung 75% \&uuml;berschreitet</g'
				mysed 's/>Top right: About</>Oben Rechts: \&Uuml;ber</g'
				mysed 's/>GitHub: Link to the Pi-hole repository</>GitHub: Verkn\&uuml;pfung zur Pi-hole Quelle</g'
				mysed "s/>Details: Link to Jacob Salmela's blog with some more details, describing also the concept of the Pi-hole</>Details: Verkn\&uuml;pfung zu Jacob Salmelas Blog mit weiteren Details, die auch das Pi-Hole-Konzept beschreiben</g"
				mysed 's/>Updates: Link to list of releases</>Aktualisierungen: Verkn\&uuml;pfung zur Liste der Releases</g'
				mysed 's/>Session timer: Shows the time remaining until the current login session expires.</>Sitzungs-Timer: Zeigt die verbleibende Zeit bis zum Ablauf der aktuellen Anmeldesitzung an.</g'
				#mysed 's/>Dashboard</>Instrumententafel</g' # Instrumententafel ist eine ungeeignete Übersetzung
				mysed 's/>On the dashboard, you can see various Pi-hole statistics:</>Im Dashboard sind verschiedene Pi-Hole-Statistiken:</g'
				mysed 's/>Summary: A summary of statistics showing how many total DNS queries have been blocked today, what percentage of DNS queries have been blocked, and how many domains are in the compiled ad list. This summary is updated every 10 seconds.</>Zusammenfassung: Eine Zusammenfassung der Statistiken, aus der hervorgeht, wie viele DNS-Abfragen heute insgesamt blockiert wurden, wie viel Prozent der DNS-Abfragen blockiert wurden und wie viele Dom\&auml;nen in der kompilierten Anzeigenliste enthalten sind. Diese Zusammenfassung wird alle 10 Sekunden aktualisiert.</g'
				mysed 's/>Queries over time: Graph showing DNS queries (total and blocked) over 10 minute time intervals. More information can be acquired by hovering over the lines. This graph is updated every 10 minutes.</>Abfragen im Zeitverlauf: Diagramm mit DNS-Abfragen (insgesamt und blockiert) in Zeitintervallen von 10 Minuten. Weitere Informationen erhalten Sie, wenn Sie den Mauszeiger über die Zeilen halten. Dieses Diagramm wird alle 10 Minuten aktualisiert.</g'
				mysed 's/>Query Types: Identifies the types of processed queries</>Abfragetypen: Identifiziert die Typen der verarbeiteten Abfragen</g'
				mysed 's/>Forward Destinations: Shows to which upstream DNS the permitted requests have been forwarded to.</>Weiterleitungsziele: Zeigt an, an welches Upstream-DNS die zul\&auml;ssigen Anforderungen weitergeleitet wurden.</g'
				mysed 's/>Top Domains: Ranking of requested sites by number of DNS lookups.</>Top-Dom\&auml;nen: Ranking der angeforderten Websites nach Anzahl der DNS-Lookups.</g'
				mysed 's/>Top Advertisers: Ranking of requested advertisements by number of DNS lookups.</>Top Inserent: Einstufung der angeforderten Werbung nach Anzahl der DNS-Lookups.</g'
				mysed 's/>Top Clients: Ranking of how many DNS requests each client has made on the local network.</>Top-Systeme: Rangfolge der DNS-Anforderungen, die jedes System im lokalen Netzwerk gestellt hat.</g'
				mysed 's/>The Top Domains and Top Advertisers lists may be hidden depending on the privacy Settings on the settings page</>Die Listen "Top Dom\&auml;nen" und "Top Inserent" werden möglicherweise in Abh\&uuml;ngigkeit von den Datenschutzeinstellungen auf der Einstellungsseite ausgeblendet</g'

				mysed 's/>Note that the login session does <em>not<\/em> expire on the dashboard, as the summary is updated every 10 seconds which refreshes the session.</>Beachten Sie, dass die Anmeldesitzung im Dashboard <em>nicht<\/em> abl\&auml;uft, da die Zusammenfassung alle 10 Sekunden aktualisiert wird, wodurch die Sitzung aktualisiert wird.</g'

			fi

			if [[ "$i" = */taillog.php ]]; then
				mysed "s/Output the last lines of the pihole.log file (live)/Ausgabe der letzten Zeilen der Datei pihole.log (live)/g"
			fi
			if [[ "$i" = */taillog-FTL.php ]]; then
				mysed "s/Output the last lines of the pihole-FTL.log file (live)/Ausgabe der letzten Zeilen der Datei pihole-FTL.log (live)/g"
			fi
			if [[ "$i" = */taillog-FTL.php || "$i" = */taillog.php ]]; then
				mysed "s/> Automatic scrolling on update</> Beim Aktualisieren automatisch bl\&auml;ttern</g"
			fi


			if [[ "$i" = */scripts/pi-hole/php/footer.php || "$i" = */scripts/pi-hole/php/header.php ]]; then
				# Footer und Header
				mysed "s/>(Update available\!)</>(Aktualisierung verf\&uuml;gbar\!)</g"
				
				mysed "s/>Web Interface Version </>Web Schnittstellen Version </g"
			fi

			# Im Footer eine zus\&auml;tzliche Angabe ausgeben
			if [[ "$i" = */scripts/pi-hole/php/footer.php ]]; then
				mysed '/if($FTL_update){ ?>*/ s/$/\n - <strong><a href="https:\/\/github.com\/BigBen2003\/pi-hole-gui-german">Deutsche \&Uuml;bersetzung<\/a><\/strong>/'
				
				mysed "s/> Donate<\/a><\/strong> if you found this useful.</> Spende<\/a><\/strong> wenn Du dieses n\&uuml;tzlich findest.</g"
			fi

			# Im header ein zus\&auml;tzliches script einbinden:
			if [[ "$i" = */scripts/pi-hole/php/header.php ]]; then
				mysed "s/>Logout</>Abmelden</g"
				mysed "s/>Login</>Anmelden</g"

				mysed "s/>Session is valid for </>Sitzung ist g\&uuml;ltig f\&uuml;r </g"


				mysed 's/<\/head>/\n	<script src="germanFiles\/Funcs.js"><\/script>\n\n<\/head>/g'

				mysed 's/> DNS service not running</> DNS-Dienst l\&auml;uft nicht</g'

				mysed 's/echo round($celsius,1) . "&nbsp;&deg;C";/echo number_format(round($celsius,1),1,",",".") \. "\&nbsp;\&deg;C";/g'
				mysed 's/\" . $loaddata\[0\] . "/\" . number_format($loaddata\[0\],2,",",".") . "/g'
				mysed 's/\" . $loaddata\[1\] . "/\" . number_format($loaddata\[1\],2,",",".") . "/g'
				mysed 's/\". $loaddata\[2\] . "/\" . number_format($loaddata\[2\],2,",",".") . "/g'
				mysed 's/\\"Detected \$nproc cores\\"/\\"Erkannte \$nproc Kerne\\"/g'
				mysed "s/\" . sprintf(\"%\.1f\",100\.0\*\$memory_usage) \. \"/\" . number_format(sprintf(\"%\.1f\",100\.0\*\$memory_usage),1,\",\",\"\.\") \. \"/g"
				
				# Menu
				mysed "s/class=\"header\">MAIN NAVIGATION<\/li>/class=\"header\">HAUPTNAVIGATION<\/li>/g"
				mysed "s/<span>Dashboard<\/span>/<span>Übersicht<\/span>/g"
				
				mysed "s/>Long term data</>Langzeitdaten</g"

				mysed "s/>Graphics</>Grafiken</g"
				mysed "s/>Top Lists</>Top Listen</g"
				
				mysed "s/>Whitelist</>Wei\&szlig;e Liste</g"
				mysed "s/>Blacklist</>Schwarze Liste</g"

				mysed "s/>Disable\&nbsp;\&nbsp;\&nbsp;</>Abschalten\&nbsp;\&nbsp;\&nbsp;</g"
				mysed "s/>Disable</>Abschalten</g"
				mysed "s/>Enable\&nbsp;\&nbsp;\&nbsp;</>Einschalten\&nbsp;\&nbsp;\&nbsp;</g"
#
				mysed "s/>Permanently</>Permanent</g"
				mysed "s/>For 10 seconds</>F\&uuml;r 10 Sekunden</g"
				mysed "s/>For 30 seconds</>F\&uuml;r 30 Sekunden</g"
				mysed "s/>For 5 minutes</>F\&uuml;r 5 Minuten</g"
				mysed "s/>Custom time</>Benutzerdefinierte Zeit</g"
				mysed "s/>Network</>Netzwerk</g"

				mysed "s/>Tools</>Werkzeuge</g"
				mysed "s/>Update Gravity</>Aktualisierung Gravity</g"
				mysed "s/>Query Lists</>Abfragelisten</g"
				mysed "s/>Audit log</>Pr\&uuml;fprotokoll</g"
				mysed "s/>Tail pihole.log</>pihole.log anzeigen</g"
				mysed "s/>Tail pihole-FTL.log</>pihole-FTL.log anzeigen</g"
				
				mysed "s/>Help</>Hilfe</g"
				mysed "s/<\/i> Load:/<\/i> Auslst.:/g"
				mysed "s/i> Active/i> Aktiv/g"
			fi

			if [[ "$i" = */scripts/pi-hole/php/header.php || "$i" = */admin/debug.php ]]; then
				mysed "s/>Generate debug log</>Erstelle debug-LOG-Datei</g"
			fi
			if [[ "$i" = */admin/debug.php ]]; then
				mysed "s/> Upload debug log and provide token once finished</> Lade das Debug-Protokoll hoch und stelle das Token bei Fertigstellung bereit.</g"
				mysed "s/>Once you click this button a debug log will be generated and can automatically be uploaded if we detect a working internet connection.</>Sobald Sie auf diese Schaltfl\&auml;che klicken, wird ein Debug-Protokoll erstellt, das automatisch hochgeladen werden kann, wenn eine funktionierende Internetverbindung erkannt wird.</g"
			fi

			
			if [[ "$i" = */scripts/pi-hole/php/header.php ]]; then
				mysed "s/Memory usage:/Speichernutzung:/g"
			fi
			
			if [[ "$i" = */scripts/pi-hole/php/header.php || "$i" = */help.php ]]; then
				
				mysed "s/>Query Log</>Abfragen Protokoll</g"
				mysed "s/>Settings</>Einstellungen</g"
				mysed "s/>Donate</>Spenden</g"
			fi
			
			if [[ "$i" = */scripts/pi-hole/php/loginpage.php ]]; then
				mysed "s/>Sign in to start your session</>Melden Sie sich an, um Ihre Sitzung zu starten</g"
				mysed "s/placeholder=\"Password\"/placeholder=\"Passwort\"/g"
				mysed "s/> \&rarr; Log in and go to requested page (/> \&rarr; Loggen Sie sich ein und gehen Sie zur gew\&uuml;nschten Seite (/g"
				mysed "s/>Ctrl+Return</>Strg+Return</g"
				mysed "s/> \&rarr; Log in and go to Settings page</> \&rarr; Loggen Sie sich ein und gehen Sie zur Einstellung-Seite</g"
				mysed "s/>Forgot password</>Passwort vergessen</g"
				mysed "s/>Verify that cookies are allowed for </>Stellen Sie sicher, dass Cookies zul\&auml;ssig sind f\&uuml;r </g"
				mysed "s/> Wrong password!</> Falsches Passwort!</g" "$i"
				mysed "s/>Remember me for 7 days</>Erinnere dich an mich f\&uuml;r 7 Tage</g"
				
				mysed "s/>\&nbsp;\&nbsp;\&nbsp;Log in</>\&nbsp;\&nbsp;\&nbsp;Einloggen</g"

				mysed "s/After installing Pi-hole for the first time, a password is generated and displayed to the user. The/Nach der erstmaligen Installation von Pi-hole wird ein Passwort generiert und dem Benutzer angezeigt. Das/g"
				mysed "s/password cannot be retrieved later on, but it is possible to set a new password (or explicitly disable/Passwort kann sp\&auml;ter nicht mehr abgerufen werden, aber es ist m\&ouml;glich, ein neues Passwort festzulegen (oder/g"
				mysed "s/the password by setting an empty password) using the command/das Passwort explizit zu deaktivieren, indem Sie ein leeres Passwort festlegen), indem Sie den Befehl verwenden:/g"
			fi

			if [[ "$i" = */db_lists.php ]]; then
				mysed 's/>Compute Top Lists from the Pi-hole query database</>Top-Listen aus der Pi-Hole-Abfragedatenbank berechnen</g'
				mysed 's/>Top Domains</>Top Dom\&auml;nen</g'
				mysed 's/>Top Clients</>Top Systeme</g'
				
			fi

			if [[ "$i" = */admin/network.php ]]; then
				mysed "s/>Network overview</>Netezwerk\&uuml;bersicht</g"
				mysed "s/>IP address</>IP Adresse</g"
				mysed "s/>Hardware address</>Hardware Adresse</g"
				mysed "s/>Interface</>Schnittstelle</g"
				mysed "s/>Hostname</>Systemname</g"
				mysed "s/>First seen</>Erstes Auftreten</g"
				mysed "s/>Last Query</>Letzte Abfrage</g"
				mysed "s/>Number of queries</>Abfragen-Anzahl</g"
				mysed "s/>Uses Pi-hole</>Nutzt Pi-Hole</g"
				mysed "s/>Background color: Last query from this device seen ...</>Hintergrundfarbe: Letze Abfrage von diesem Ger\&auml;t gesehen ...</g"
				mysed "s/>just now</>Jetzt gerade</g"
				mysed "s/>... to ...</>... bis ...</g"
				mysed "s/>24 hours ago</>vor 24 Stunden</g"
				mysed "s/>\&gt; 24 hours ago</>vor mehr als 24 Stunden</g"
 				mysed "s/>Device does not use Pi-hole</>Ger\&auml;t  verwendet kein PI-Hole</g"
			fi


			if [[ "$i" = */db_lists.php || "$i" = */db_graph.php || "$i" = */db_queries.php ]]; then
				mysed "s/Depending on how large of a range you specified, the request may time out while Pi-hole tries to retrieve all the data./Je nachdem, wie gro\&szlig; der von Ihnen angegebene Bereich ist, tritt m\&ouml;glicherweise eine Zeit\&uuml;berschreitung auf, w\&auml;hrend Pi-hole versucht, alle Daten abzurufen./g"
			fi

			if [[ "$i" = */db_graph.php ]]; then
				mysed "s/Queries over the selected time period/Abfragen \&uuml;ber den ausgew\&auml;hlten Zeitraum/g"
			fi

			if [[ "$i" = */scripts/pi-hole/js/index.js || "$i" = */scripts/pi-hole/js/db_graph.js ]]; then
				mysed "s/Total DNS Queries/Gesamte DNS-Abfragen/g"
				mysed "s/Blocked DNS Queries/Blockierte DNS Abfragen/g"
			fi

			if [[ "$i" = */scripts/pi-hole/js/index.js ]]; then
				mysed "s/\"only A + AAAA queries (\"/\"Nur A + AAAA-Abfragen (insgesamt \"/g"
				mysed 's/ + data\["dns_queries_all_types"\] + / + formatNumber(data\["dns_queries_all_types"\]) + /g'
				mysed 's/\? data\[header\] + "%" \: data\[header\]/? formatNumber(data\[header\]) + "%" \: formatNumber(data\[header\])/g'

				mysed "s/\" in total)\"/\")\"/g"
				mysed "s/\"A: IPv4 queries\"/\"A: IPv4 Abfragen\"/g"
				mysed "s/\"AAAA: IPv6 queries\"/\"AAAA: IPv6 Abfragen\"/g"
				mysed "s/\"Query types from \"+from+\" to \"+to;/\"Abfragetypen von \"+from+\" bis \"+to;/g"
				mysed "s/\"Query types\"/\"Abfrage Typen\"/g"
			
				mysed "s/\"Forward destinations from \"+from+\" to \"+to;/\"Ziele weiterleiten von \"+from+\" nach \"+to;/g"
				mysed "s/\"Forward destinations\"/\"Ziele weiterleiten\"/g"

				mysed 's/todayElement\.text() !== data\[today\] \&\&/todayElement\.text() !== formatNumber(data\[today\]) \&\&/g'
				mysed 's/todayElement\.text() !== data\[today\] + \"%\" \&\&/todayElement\.text() !== formatNumber(data\[today\] + \"%\") \&\&/g'
				
				mysed "s/Upstreams from \"+from+\" to /Upstreams von \"+from+\" nach /g"
				
				mysed "s/Client activity from \"+from+\" to /System Aktivit\&auml;ten von \"+from+\" nach /g"
			
			fi
			

			if [[ "$i" = */admin/queryads.php ]]; then
				mysed "s/>Find Blocked Domain In Lists</>Finde blockierte Dom\&auml;ne in Listen</g"
				mysed 's/"Domain to look for (example.com or sub.example.com)"/"zu suchende Dom\&auml;ne (beispiel.de oder www.beispiel.de)"/g'
				mysed "s/>Search partial match</>Suche Teil\&Uuml;bereinstimmung</g"
				mysed "s/>Search exact match</>Suche genaue \&Uuml;bereinstimmung</g"
			fi


			if [[ "$i" = */index.php ]]; then
				mysed "s/Query Types/Abfragetypen/g"
			fi

			if [[ "$i" = */scripts/pi-hole/js/footer.js ]]; then
				mysed "s/ena.text(\"Enable\")/ena.text(\"Anschalten\")/g"
				mysed "s/\"Enable (/\"Anschalten (/g"
			fi

			if [[ "$i" = *jquery.dataTables.min.js* ]]; then
				mysed "s/\"Showing 0 to 0 of 0 entries\"/\"Zeige 0 bis 0 von 0 Eintr\&auml;gen\"/g"
				mysed "s/\"(filtered from _MAX_ total entries)\"/\"(gefiltert aus _MAX_ Gesamteintr\&auml;gen)\"/g"
				mysed "s/\"Show _MENU_ entries\"/\"Zeige _MENU_ Eintr\&auml;ge\"/g"
				mysed "s/\"No matching records found\"/\"Keine \&uuml;bereinstimmende Eintr\&auml;ge gefunden\"/g"

				mysed "s/\": activate to sort column ascending\"/\": Aktivieren, um die Spalte aufsteigend (A-Z) zu sortieren\"/g"
				mysed "s/\": activate to sort column descending\"/\": Aktivieren, um die Spalte absteigend (Z-A) zu sortieren\"/g"
				mysed "s/\"No data available in table\"/\"Keine Tabelleneintr\&auml;ge verf\&uuml;gbar\"/g"
				mysed "s/\"Showing _START_ to _END_ of _TOTAL_ entries\"/\"Anzeige _START_ bis _END_ von _TOTAL_ Eintr\&auml;ge\"/g"
				
				mysed 's/"Previous"/"Vorherige"/g'
				mysed 's/"Next"/"N\&auml;chste"/g'
				mysed 's/"Search:"/"Suche:"/g'
			fi

			if [[ "$i" = */scripts/pi-hole/js/queries.js ]]; then
				mysed "s/\"Blocked (gravity)\"/\"Gesperrt (Gravity)\"/g"
				mysed "s/>(forwarded)\"/>(weitergel.)\"/g"
				mysed "s/\"Blocked </\"Gesperrt </g"
				mysed "s/>(external, />(extern, /g"
				mysed "s/\"Unknown (/\"Unbekannt (/g"

				mysed 's/"The server took too long to send the data."/"Der Server hat zu lange gebraucht, um die Daten zu senden."/g'
				mysed "s/\"An error occured while loading the data: Connection refused. Is FTL running?\"/\"Beim Laden der Daten ist ein Fehler aufgetreten: Verbindung abgelehnt. L\&auml;uft der FTL Dienst?\"/g"
				mysed "s/\"An unknown error occured while loading the data./\"Beim Laden der Daten ist ein unbekannter Fehler aufgetreten./g"
				mysed "s/>SECURE</>SICHER</g"
				mysed "s/>INSECURE</>UNSICHER</g"
				mysed "s/>BOGUS</>SCHEIN</g"
				mysed "s/>ABANDONED</>VERLASSEN</g"
				mysed "s/>UNKNOWN</>UNBEKANNT</g"

				mysed 's/"Click to show only " + this.innerHTML + " queries"/"Klicken Sie hier, um nur " + this.innerHTML + "-Abfragen anzuzeigen"/g'
				mysed "s/\"Click to show only queries with domain \" + this.innerHTML/\"Klicken Sie hier, um nur Abfragen mit der Domain \" + this.innerHTML+\" anzuzeigen\"/g"
				mysed "s/\"Click to show only queries made by \" + this.innerHTML/\"Klicken Sie hier, um nur Abfragen von \" + this.innerHTML + \" anzuzeigen\"/g"	
			fi

			if [[ "$i" = *jquery.dataTables.min.js* ]]; then
				mysed "s/\"Processing...\"/\"wird bearbeitet...\"/g"
				mysed "s/\"Loading...\"/\"wird geladen...\"/g"
			fi

			if [[ "$i" = */settings.php* ]]; then
				mysed "s/>Top Lists</>Top Listen</g"
				mysed "s/>Blocklists</>Sperrlisten</g"
				mysed "s/>API \/ Web interface</>API \/ Web Schnittstellen</g"
				mysed "s/>Privacy</>Privatsph\&auml;re</g"

				mysed "s/>Network Information</>Netzwerk Information</g"
				mysed "s/>Pi-hole Ethernet Interface:</>Pi-hole Ethernet Schnittstelle:</g"
				mysed "s/>Pi-hole IPv4 address:</>Pi-hole IPv4 Adresse:</g"
				mysed "s/>Pi-hole IPv6 address:</>Pi-hole IPv6 Adresse:</g"
				mysed "s/>Pi-hole hostname:</>Pi-hole Hostname:</g"

				mysed "s/>FTL version:</>FTL Version:</g"
				mysed "s/>Process identifier (PID):</>Prozesskennung (PID):</g"
				mysed "s/>Time FTL started:</>Startzeit FTL:</g"
				mysed "s/>User \/ Group:</>Benutzer \/ Gruppe:</g"
				mysed "s/>Total CPU utilization:</>Gesamt CPU-Auslastung:</g"
				mysed "s/>Memory utilization:</Speicherauslastung:/g"
				mysed "s/>Used memory:</>Verwendeter Speicher:</g"
				mysed "s/>DNS cache size:</>DNS-Cache-Gr\&ouml;\&szlig;e:</g"
				mysed "s/>DNS cache insertions:</>DNS-Cache-Einf\&uuml;gungen:</g"
				mysed "s/>DNS cache evictions:</>DNS-Cache-R\&auml;umungen:</g"

				mysed "s/>The FTL service is offline!</>Der FTL-Dienst ist offline!</g"
				mysed "s/See also our </Siehe auch unsere </g"
				mysed "s/>Danger Zone!</>Gefahrenzone!</g"

				mysed "s/>Disable query logging</>Abfrageprotokollierung deaktivieren</g"
				mysed "s/>Disable query logging and flush logs</>Abfrprot. deakt.+Prot-Eintr\&auml;ge l\&ouml;schen</g"
				mysed "s/>Restart DNS resolver</>DNS-Aufl\&ouml;sung neu starten</g"
				mysed "s/>Flush logs</>Protolleintr\&auml;ge l\&ouml;schen</g"
				mysed "s/>Power off system</>System ausschalten</g"
				mysed "s/>Restart system</>System neustarten</g"

				mysed "s/\"There was a problem applying your settings.<br>Debugging information:<br>PHP error /\"Beim Anwenden Ihrer Einstellungen ist ein Problem aufgetreten.<br>Debugging-Informationen:<br>PHP Fehler /g"
				mysed "s/\"unknown\"/\"unbekannt\"/g"
				mysed "s/>Blocklists used to generate Pi-hole's Gravity: </>Sperrlisten nutzen zur Erzeugung Pi-hole's Gravit\&auml;t: </g"
				mysed "s/<th>Enabled<\/th>/<th>Aktiviert<\/th>/g"
				mysed "s/<th>List<\/th>/<th>Liste<\/th>/g"
				mysed "s/<strong>Important: <\/strong>/<strong>Wichtig: <\/strong>/g"
				mysed "s/\"Enter one URL per line to add new blocklists\"/\"Geben Sie eine URL pro Zeile ein, um neue Sperrlisten hinzuzuf\&uuml;gen\"/g"
				mysed "s/>Save</>Speichern</g"
				mysed "s/>Save and Update when you're done!</>Speichern und aktualisieren, sobald Sie fertig sind!</g"
				mysed "s/>Save and Update</>Speichern und aktualisieren</g"
				mysed "s/>Make sure your router's DHCP server is disabled when using the Pi-hole DHCP server!</>Stellen Sie sicher, dass das DHCP-Server Ihres Routers deaktiviert ist, wenn Sie den Pi-Hole-dHCP-Server verwenden!</g"
				mysed "s/>Range of IP addresses to hand out</>Bereich der zu verteilenden IP-Adressen</g"
				mysed "s/\?>disabled</\?>abgeschaltet</g"
				mysed "s/>Router (gateway) IP address</>Router (Gateway) IP Adresse</g"
				mysed "s/>Advanced DHCP settings</>Erweiterte DHCP Einstellungen</g"
				mysed "s/>Pi-hole domain name</>Pi-Hole Domain-Name</g"
				mysed "s/>DHCP lease time</>DHCP-Miet-Zeit</g"

				mysed "s/>Hint: 0 = infinite, 24 = one day, 168 = one week, 744 = one month, 8760 = one year</>Hinweis: 0 = unendlich, 24 = ein Tag, 168 = eine Woche, 744 = ein Monat, 8760 = ein Jahr</g"
				mysed "s/>Enable IPv6 support (SLAAC + RA)</>IPv6-Unterst\&uuml;tzung (SLAAC + RA) aktivieren</g"
				mysed "s/>Enable DHCP rapid commit (fast address assignment)</>Schnelles Festschreiben von DHCP (schnelle Adresszuweisung)  aktivieren</g"
				mysed "s/>DHCP leases</>DHCP-Mieten</g"
				mysed "s/>Currently active DHCP leases</>Derzeit aktive DHCP-Mieten</g"
				mysed "s/>MAC address</>MAC Adresse</g"
				mysed "s/>IP address</>IP Adresse</g"
				mysed "s/\"Lease type: IPv</\"Lease-Typ IPv</g"
				mysed "s/>Remaining lease time: </>Verbleibende Mietzeit: </g"
				mysed "s/>Static DHCP leases configuration</>Statische DHCP-Miet-Einstellung</g"

				mysed "s/>Specifying the MAC address is mandatory and only one entry per MAC/>Die Angabe der MAC-Adresse ist obligatorisch und nur ein Eintrag pro MAC-/g"
				mysed "s/address is allowed. If the IP address is omitted and a host name is/Adresse ist zul\&auml;ssig. Wenn die IP-Adresse weggelassen und ein Hostname/g"
				mysed "s/given, the IP address will still be generated dynamically and the/angegeben wird, wird die IP-Adresse weiterhin dynamisch generiert und der/g"
				mysed "s/specified host name will be used. If the host name is omitted, only/angegebene Hostname verwendet. Wenn der Hostname weggelassen wird, dann/g"
				mysed "s/a static lease will be added.</wird nur eine statische Miete hinzugef\&uuml;gt.</g"

				mysed "s/>Upstream DNS Servers</>Upstream DNS-Server</g"
				mysed "s/> disabled </> abgschaltet </g"
				mysed "s/>ECS (Extended Client Subnet) defines a mechanism for recursive resolvers to send partial client IP address information to authoritative DNS name servers. Content Delivery Networks (CDNs) and latency-sensitive services use this to give geo-located responses when responding to name lookups coming through public DNS resolvers. <em>Note that ECS may result in reduced privacy.</>ECS (Extended Client Subnet) definiert einen Mechanismus f\&uuml;r rekursive Resolver, um teilweise IP-Adressinformationen des Clients an autorisierende DNS-Nameserver zu senden. Content Delivery Networks (CDNs) und latenzempfindliche Dienste verwenden diese Option, um geografische Antworten auf Namenssuchen zu geben, die \&uuml;ber \&ouml;ffentliche DNS-Resolver eingehen.<em>Beachten Sie, dass ECS zu einer Einschr\&auml;nkung der Privatsph\&auml;re f\&uuml;hren kann.</g"
				mysed "s/>Custom 1 (IPv4)</>Benutzerdef. 1 (IPv4)</g"
				mysed "s/>Custom 2 (IPv4)</>Benutzerdef. 2 (IPv4)</g"
				mysed "s/>Custom 3 (IPv6)</>Benutzerdef. 3 (IPv6)</g"
				mysed "s/>Custom 4 (IPv6)</>Benutzerdef. 4 (IPv6)</g"

				mysed "s/>Interface listening behavior</>Schnittstellen abh\&ouml;r Verhalten</g"
				mysed "s/>Allows only queries from devices that are at most one hop away (local devices)</>Erm\&ouml;glicht nur Abfragen von Ger\&auml;ten, die h\&ouml;chstens einen Sprung entfernt sind (lokale Ger\&auml;te)</g"
				mysed "s/>Listen only on interface </>Abh\&ouml;ren nur auf Schnittstelle </g"
				mysed "s/>Listen on all interfaces, permit all origins</>Alle Schnittstellen abh\&ouml;ren, alle Quellen zulassen</g"
				mysed "s/>Listen on all interfaces</>Alle Schnittstellen abh\&ouml;ren</g"

				mysed "s/>Note that the last option should not be used on devices which are/>Beachten Sie, dass die letzte Option nicht f\&uuml;r Ger\&auml;te verwendet werden/g"
				mysed "s/directly connected to the Internet. This option is safe if your/sollte, die direkt mit dem Internet verbunden sind. Diese Option ist/g"
				mysed "s/Pi-hole is located within your local network, i.e. protected behind/sicher, wenn sich Ihr Pi-Hole in Ihrem lokalen Netzwerk befindet, d. H./g"
				mysed "s/your router, and you have not forwarded port 53 to this device. In/Hinter Ihrem Router gesch\&uuml;tzt ist und Sie Port 53 nicht an dieses Ger\&auml;t/g"
				mysed "s/virtually all other cases you have to make sure that your Pi-hole is/weitergeleitet haben. In praktisch allen anderen F\&auml;llen m\&uuml;ssen Sie sicher-/g"
				mysed "s/properly firewalled.</stellen, dass Ihr Pi-Hole ordnungsgem\&auml;\&szlig; durch eine Firewall gesch\&uuml;tzt ist.</g"

				mysed "s/DHCP Settings/DHCP Einstellungen/g"
				mysed "s/>From</>Von</g"
				mysed "s/>To</>Bis</g"
				mysed "s/>Domain</>Dom\&auml;ne</g"
				mysed "s/>Lease time in hours</>Mietdauer in Stunden</g"

				mysed "s/>DHCP server enabled</>DHCP Server aktivieren</g"

				mysed "s/Advanced DNS settings/Erweiterte DNS Einstellungen/g"
				mysed "s/Never forward non-FQDNs/Leite niemals Nicht-FQDNs weiter/g"
				mysed "s/Never forward reverse lookups for private IP ranges/Leite niemals Reverse-Lookups f\&uuml;r private IP-Bereiche weiter/g"

				mysed "s/>Note that enabling these two options may increase your privacy/>Beachten Sie, dass das Aktivieren dieser beiden Optionen Ihre Privatsph\&auml;re/g"
				mysed "s/slightly, but may also prevent you from being able to access/geringf\&uuml;gig verbessern kann, Sie jedoch auch daran hindern kann, auf lokale Hostnamen zuzugreifen,/g"
				mysed "s/local hostnames if the Pi-hole is not used as DHCP server</wenn das Pi-Hole nicht als DHCP-Server verwendet wird</g"

				mysed "s/>Use DNSSEC</>Benutze DNSSEC</g"

				mysed "s/>Conditional Forwarding</>Bedingte Weiterleitung</g"

				mysed "s/>Validate DNS replies and cache DNSSEC data. When forwarding DNS/>Überpr\&uuml;fen Sie die DNS-Antworten und speichern Sie die DNSSEC-/g"
				mysed "s/queries, Pi-hole requests the DNSSEC records needed to validate/Daten im Cache. Bei der Weiterleitung von DNS-Abfragen fordert/g"
				mysed "s/the replies. If a domain fails validation or the upstream does not/Pi-hole die zur Validierung der Antworten erforderlichen DNSSEC-/g"
				mysed "s/support DNSSEC, this setting can cause issues resolving domains./Eintr\&auml;ge an. Wenn eine Domain die Validierung nicht besteht oder/g"
				mysed "s/Use Google, Cloudflare, DNS.WATCH, Quad9, or another DNS/der Upstream DNSSEC nicht unterst\&uuml;tzt, kann diese Einstellung/g"
				mysed "s/server which supports DNSSEC when activating DNSSEC. Note that/Probleme beim Aufl\&ouml;sen von Domains verursachen. Verwenden Sie/g"
				mysed "s/the size of your log might increase significantly/Google, Cloudflare, DNS.WATCH, Quad9 oder einen anderen DNS-Server,/g"
				mysed "s/when enabling DNSSEC. A DNSSEC resolver test can be found/der DNSSEC unterst\&uuml;tzt, wenn Sie DNSSEC aktivieren. Beachten Sie, dass die Gr\&ouml;\&szlig;e Ihres Protokolls beim Aktivieren von DNSSEC m\&ouml;glicherweise erheblich zunimmt. Einen DNSSEC-Resolvertest finden Sie /g"
				#mysed "s/<a href=\"http:\/\/dnssec.vs.uni-due.de/\" target=\"_blank\">here</a>.</<a href=\"http:\/\/dnssec.vs.uni-due.de/\" target=\"_blank\">hier</a>.</g"
				mysed "s/_blank\">here</_blank\">hier</g"
				#mysed "s/<a href=\"http:\/\/dnssec.vs.uni-due.de/\" target=\"_blank\">here</a>\.</TEST/g"

				mysed "s/>If not configured as your DHCP server, Pi-hole won't be able to/>Wenn Pi-hole nicht als DHCP-Server konfiguriert ist, kann es die Namen/g"
				mysed "s/determine the names of devices on your local network.  As a/ der Ger\&auml;te in Ihrem lokalen Netzwerk nicht ermitteln./g"
				mysed "s/result, tables such as Top Clients will only show IP addresses.</ Daher werden in Tabellen wie Top Clients nur IP-Adressen angezeigt.</g"

				mysed "s/>One solution for this is to configure Pi-hole to forward these/>Eine L\&ouml;sung hierf\&uuml;r besteht darin, Pi-hole so zu konfigurieren,/g"
				mysed "s/requests to your DHCP server (most likely your router), but only for devices on your/dass diese Anforderungen an Ihren DHCP-Server (h\&ouml;chstwahrscheinlich/g"
				mysed "s/home network.  To configure this we will need to know the IP/an Ihren Router) weitergeleitet werden, jedoch nur f\&uuml;r Ger\&auml;te in/g"
				mysed "s/address of your DHCP server and the name of your local network.</Ihrem Heimnetzwerk. Um dies zu konfigurieren, m\&uuml;ssen wir die IP-Adresse Ihres DHCP-Servers und den Namen Ihres lokalen Netzwerks kennen.</g"

				mysed "s/>Note: The local domain name must match the domain name specified/>Hinweis: Der lokale Dom\&auml;nenname muss mit dem in Ihrem DHCP-Server/g"
				mysed "s/in your DHCP server, likely found within the DHCP settings.</angegebenen Dom\&auml;nennamen \&uuml;bereinstimmen, der wahrscheinlich in den DHCP-Einstellungen enthalten ist.</g"

				mysed "s/>Use Conditional Forwarding</>Benutze begingte Weiterleitung</g"

				mysed "s/>IP of your router</>IP von Deinem Router</g"
				mysed "s/>Local domain name</>Lokaler Dom\&auml;nenname</g"

				mysed "s/>API settings</>API Einstellungen</g"
				mysed "s/>Exclude the following domains from being shown in</>Folgende Dom\&auml;nen werden in den Listen ausgeblendet</g"
				mysed "s/Top Domains \/ Top Advertisers</>Top Dom\&auml;nen \/ Top Werbetreibende</g"
				mysed 's/"Enter one domain per line"/"Gib eine Dom\&auml;ne pro Zeile ein"/g'
				mysed "s/>Top Clients</>Top Systeme</g"
				mysed "s/\"Enter one IP address or host name per line\"/\"Gib eine IP-Adresse oder Hostnamen pro Zeile ein\"/g"
				mysed "s/>Query Log</>Abfrage Protokoll</g"
				mysed "s/> Show permitted domain entries</> Zul\&auml;ssige Dom\&auml;nen-Eintr\&auml;ge anzeigen</g"
				mysed "s/> Show blocked domain entries</> Blockierte Dom\&auml;nen-Eintr\&auml;ge anzeigen</g"
				mysed "s/>Show API token</>API-Token anzeigen</g"
				mysed "s/>Web interface settings</>Web Schnittstellen Einstellungen</g"
				mysed "s/>Interface appearance</>Oberfl\&auml;chendarstellung</g"
				mysed "s/>Use boxed layout (helpful when working on large screens)</>Box-Darstellung verwenden (sinnvoll bei gro\&szlig;en Bildschirmen)</g"
				mysed "s/>CPU Temperature Unit</>CPU-Temperatureinheit</g"
				mysed "s/>Administrator Email Address</>Email-Adresse vom Administrator</g"

				mysed "s/>Privacy settings</>Datenschutzeinstellungen</g"
				mysed "s/>DNS resolver privacy level</>DNS-Resolver Datenschutzstufe</g"
				mysed "s/>Specify if DNS queries should be anonymized, available options are:/>Gib an, ob die DNS-Anfragen anonymisiert werden sollen. Folgende Optionen stehen zu Auswahl:/g"
				mysed "s/>Show everything and record everything<br>Gives maximum amount of statistics</>Alles anzeigen und alles aufzeichnen<br>Gibt maximale Anzahl von Statistiken</g"
				mysed "s/>Hide domains: Display and store all domains as \"hidden\"<br>This disables the Top Domains and Top Ads tables on the dashboard</>Dom\auml;nen verstecken: Alle Domains als \"versteckt\" anzeigen und speichern<br>Dadurch werden die Tabellen \"Top Dom\&auml;nen\" und \"Top Werbetreibende\" im Dashboard deaktiviert</g"
				mysed "s/>Hide domains and clients: Display and store all domains as \"hidden\" and all clients as \"0.0.0.0\"<br>This disables all tables on the dashboard</>Dom\&auml;nen und Host-Systeme ausblenden: Alle Domains als \"versteckt\" und alle Host-Systeme als \"0.0.0.0\" anzeigen und speichern<br>Dadurch werden alle Tabellen im Dashboard deaktiviert</g"
				mysed "s/>Anonymous mode: This disables basically everything except the live anonymous statistics<br>No history is saved at all to the database, and nothing is shown in the query log. Also, there are no top item lists.</>Anonymer Modus: Deaktiviert im Grunde alles außer den anonymen Live-Statistiken<br>Es wird überhaupt kein Verlauf in der Datenbank gespeichert, und im Abfrageprotokoll wird nichts angezeigt. Es gibt auch keine Top-Item-Listen.</g"
				mysed "s/>No Statistics mode: This disables all statistics processing. Even the query counters will not be available.</>Kein Statistikmodus: Hiermit wird die gesamte Statistikverarbeitung deaktiviert. Sogar die Abfragez\&auml;hler sind nicht verf\&uuml;gbar.</g"
				mysed "s/>Note that regex blocking is not available when query analyzing is disabled.</>Beachten Sie, dass die Regex-Blockierung nicht verf\&uuml;gbar ist, wenn die Abfrage-Analyse deaktiviert ist.</g"
				mysed "s/>Additionally, you can disable logging to the file <code>\/var\/log\/pihole.log<\/code> using <code>sudo pihole logging off<\/code>.</>Au\&szlig;erdem kann die Protokollierung in der Datei <code>\/var\/log\/pihole.log<\/code> mithilfe von <code>sudo pihole logout<\/code> deaktiviert werden.</g"
				mysed "s/>The privacy level may be increased at any time without having to restart the DNS resolver. However, note that the DNS resolver needs to be restarted when lowering the privacy level. This restarting is automatically done when saving.</>Die Datenschutzstufe kann jederzeit erh\&ouml;ht werden, ohne dass der DNS-Resolver neu gestartet werden muss. Beachtet werden muss alerdings, dass der DNS-Resolver neu gestartet werden muss, wenn die Datenschutzstufe gesenkt wird. Dieser Neustart erfolgt automatisch beim Speichern.</g"
				mysed "s/>Warning: Pi-hole's query logging is activated. Although the dashboard will hide the requested details, all queries are still fully logged to the pihole.log file.</>Warnung: Die Abfrageprotokollierung von Pi-hole ist aktiviert. Obwohl im Dashboard die angeforderten Details ausgeblendet werden, werden alle Abfragen weiterhin vollst\&auml;ndig in der Datei pihole.log protokolliert.</g"
				mysed "s/>Apply</>Anwenden</g"

				mysed "s/>Teleporter Export/Teleporter exportieren/g"
				mysed "s/>Export your Pi-hole lists as downloadable archive</>Exportiert die Pi-Hole-Listen als herunterladbares Archiv</g"
				mysed "s/>Export</>Exportieren</g"
				mysed "s/>Teleporter Import</>Teleporter Importieren</g"
				mysed "s/>Import ...</>Importieren ...</g"
				mysed "s/   Whitelist</   Wei\&szlig;e Liste</g"
				mysed "s/   Blacklist (exact)</   Schwarze Liste (genau)</g"
				mysed "s/   Regex filters</   RegEx-Filter</g"
				mysed "s/   Audit log</   Audit Protokoll</g"
				mysed "s/>File input</>Datei hochladen</g"
				mysed "s/>Upload only Pi-hole backup files.</>Nur Pip-Hole Sicherungsdateien hochladen.</g"
				mysed "s/>Import/>Importieren/g"
				mysed "s/>The PHP extension <code>Phar<\/code> is not loaded. Please ensure it is installed and loaded if you want to use the Pi-hole teleporter.</>Die PHP-Erweiterung <code>Phar<\/code> wird nicht geladen. Bitte stellen Sie sicher, dass es installiert und geladen ist, wenn Sie den Pi-Hole-Teleporter verwenden möchten.</g"
				#mysed 's/"Resident memory is the portion of memory occupied by a process that is held in main memory (RAM). The rest of the occupied memory exists in the swap space or file system."/"Residenter Speicher ist der Teil des Speichers, der von einem Prozess belegt wird, der im Hauptspeicher (RAM) gespeichert ist. Der Rest des belegten Speichers befindet sich im Auslagerungsspeicher oder im Dateisystem."/g'
				#mysed "s/>DNS cache size:</>DNS Cache Gr\&ouml;\&szlig;e:</g"
				#mysed "s/>DNS cache insertions:</>DNS Cache Einf\&uuml;gungen:</g"
				#mysed "s/>DNS cache evictions:</>DNS Cache R\&auml;umungen:</g"
				
			fi

			if [[ "$i" = */queries.php* ]]; then
				mysed "s/\"showing\"\;/\"Anzeige\"\;/g"
				mysed "s/\"showing permitted\"\;/\"Anzeigen erlaubt\"\;/g"
				mysed "s/\"showing blocked\"\;/\"Anzeige blockiert\"\;/g"
				mysed "s/\"showing no queries (due to setting)\"\;/\"Anzeige keiner Abfrage (aufgrund der Einstellungen)\"\;/g"
				mysed "s/\" all queries within the Pi-hole log\"\;/\" aller Abfragen im Pi-Hole-Log\"\;/g"
				mysed "s/\" queries for client \"/\" Abfragen f\&uuml;r Client \"/g"
				mysed "s/\" queries for domain \"/\" Abfragen f\&uuml;r Dom\&auml;ne \"/g"
				mysed "s/\" queries within specified time interval\"/\" von Abfragen innerhalb des angegebenen Zeitintervalls\"/g"
				mysed "s/\", privacy mode enabled\"\;/\", Datenschutzmodus aktiviert\"\;/g"
				mysed "s/\" up to 100 queries\"/\" von mehr als 100 Abfragen\"/g"
				mysed "s/>show all</>Alle Anzeigen</g"
				mysed "s/>Adding </>Hinzuf\&uuml;gen /g"
				mysed "s/> to the </> zu der </g"
				mysed "s/> successfully added to the </> Erfolgreich hinzugef\&uuml;gt zu der /g"
				mysed "s/>Refresh Data</>Daten aktualisieren</g"
				mysed "s/>Timeout or Network Connection Error!</>Timeout oder Netzwerkverbindungsfehler!</g"
				mysed "s/>Recent Queries </>Letzte Abfragen </g"
				mysed "s/>\&nbsp\;Apply filtering on click on Type, Domain, and Clients</>\&nbsp\;Wenden Sie die Filterung an, indem Sie auf Typ, Dom\&auml;ne und Systeme klicken</g"
				
				mysed 's/>Clear Filters</>Filter entfernen</g'
			fi

			if [[ "$i" = */admin/gravity.php ]]; then
				mysed "s/>Update Gravity (list of blocked domains)</>Aktualisierung Gravity (Liste von blockierten Dom\&auml;men)</g"
				mysed "s/>Update</>Aktualisieren</g"
			fi

			if [[ "$i" = */scripts/pi-hole/php/gravity.php ]]; then
				mysed "s/\"Blocking list updated %a days, %H:%I ago\"/\"Sperrliste aktualisiert vor %a Tagen, %H:%I\"/g"
				mysed "s/\"Blocking list updated one day, %H:%I ago\"/\"Sperrliste aktualisiert vor einem Tag, %H:%I\"/g"
				mysed "s/\"Blocking list updated %H:%I ago\"/\"Sperrliste aktualisiert vor %H:%I\"/g"
				mysed "s/\"Blocking list not found\"/\"Sperrliste nicht gefunden\"/g"
			fi

			if [[ "$i" = */scripts/pi-hole/js/index.js ]]; then
				mysed "s/\"% of \"/\"% von \"/g"
			fi

			if [[ "$i" = */scripts/pi-hole/js/db_lists.js ]]; then
				mysed "s/\"% of \"/\"% von \"/g"
			fi

			if [[ "$i" = */index.php ]]; then
				mysed "s/\"only A + AAAA queries\"/\"Nur A + AAAA Abfragen\"/g"
				mysed "s/Queries answered by/Anfragen beantwortet von/g"

				mysed "s/>Clients (over time)</>Systeme (im Laufe der Zeit)</g"
				mysed "s/>Top Clients (total)</>Top Systeme (Gesamt)</g"
				mysed "s/>Top Clients (blocked only)</>Top Systeme (nur blockierte)</g"
				
				mysed "s/Total queries (<span id=\"unique_clients\">-<\/span> clients/Abfragen insgesamt (<span id=\"unique_clients\">-<\/span> Systeme/g"
				
				mysed "s/>Percent Blocked</>Prozentual blockiert</g"
				mysed "s/>Domains on Blocklist</>Dom\&auml;nen in Blockliste</g"
				
				mysed "s/Top Permitted Domains/Top zul\&auml;ssige Dom\&auml;nen/g"
				mysed "s/Queries over last <?php echo getinterval(); ?> hours/Abfragen der letzten <?php echo getinterval(); ?> Stunden/g"
			fi

			if [[ "$i" = */auditlog.php ]]; then
				mysed "s/>Blocked queries</>Blockierte Abfragen</g"
				mysed "s/>Allowed queries</>Erlaubte Abfragen</g"
				mysed "s/>Audit log (showing live data)</>Pr\&uuml;fungprotokoll (Anzeige Echtdaten)</g"
				
				mysed "s/><strong>Important:<\/strong> Note that black- and whitelisted domains are not automatically applied on this page to avoid restarting the DNS service too often. Instead, click on this button, to have the new settings become effective:</><strong>Wichtig:<\/strong> Beachten Sie, dass Schwarz- und Wei\&szlig;e-Listen-Domains auf dieser Seite nicht automatisch angewendet werden, um einen zu h\&auml;ufigen Neustart des DNS-Diensts zu vermeiden. Klicken Sie stattdessen auf diese Schaltfl\&auml;che, damit die neuen Einstellungen wirksam werden:</g"
				mysed "s/>Update black-\/whitelists</>Aktualisiere Schwarz-\/Wei\&szlig;-Listen</g"
			fi

			if [[ "$i" = */auditlog.js ]]; then
				mysed "s/> Audit</> Pr\&uuml;fung</g"
			fi

			if [[ "$i" = */auditlog.js || "$i" = */db_queries.js || "$i" = */queries.js ]]; then
				mysed "s/> Whitelist</> Wei\&szlig;e L.</g"
				mysed "s/> Blacklist</> Schw. L.</g"
			fi
			
			if [[ "$i" = */db_graph.php ]]; then
				mysed "s/>Compute graphical statistics from the Pi-hole query database</>Grafische Statistiken aus der PiHole-Abfragen-Datenbank</g"
			fi

			if [[ "$i" = */list.php ]]; then
				mysed "s/\"Add a domain (example.com or sub.example.com)\"/\"Hinzuf\&uuml;gen einer Dom\&auml;ne (z.B. beispiel.de oder www.beispiel.de)\"/g"
				mysed "s/echo \"Blacklist\"/echo \"Schwarze Liste\"/g"
				mysed "s/echo \"Whitelist\"/echo \"Wei\&szlig;e Liste\"/g"
				mysed 's/>Add</ title="Neuen Dom\&auml;nen-Eintrag in die Liste aufnehmen">Hinzuf.</g'
				mysed 's/id="btnRefresh"/id="btnRefresh" title="Liste neu auslesen"/g'
				mysed "s/>Exact blocking</>Genaues Blockieren</g"
				mysed "s/>Regex<\/a> \&amp; Wildcard blocking</>RegEx<\/a> \&amp; Wildcard-Blockierung</g"
				mysed "s/>Add (exact)</>Hinzuf\&uuml;gen (genau)</g"
				mysed "s/>Add (wildcard)</>Hinzuf\&uuml;gen (Platzhalter)</g"
				mysed "s/>Add (regex)</>Hinzuf\&uuml;gen (reg. Ausdr.)</g"
			fi

			if [[ "$i" = */queries.php ]]; then
				mysed "s/<th>Reply<\/th>/<th>Antwort<\/th>/g"
			fi

			if [[ "$i" = */db_queries.php ]]; then
				mysed "s/(forwarded)</(weitergel.)</g"
				mysed "s/>Queries Blocked (Wildcards)</>Abfragen blockiert (Platzhalter)</g"
				
				mysed "s/Specify date range to be queried from the Pi-hole query database/Geben Sie den Datumsbereich an, der aus der Pi-Hole-Abfragedatenbank abgefragt werden soll/g"
				
				mysed "s/Query status:/Abfrage-Status:/g"
				mysed "s/Queries Total/Abfragen insgesamt/g"
				mysed "s/Blocked (exact)/Gesperrt (genau)/g"   
				
				mysed 's/>Recent Queries</>Letzte Abfragen</g'
			fi

			if [[ "$i" = */db_queries.php || "$i" = */index.php ]]; then
				mysed "s/>Queries Blocked</>Abfragen blockiert</g"
			fi

			if [[ "$i" = */queries.php || "$i" = */db_queries.php ]]; then
				mysed "s/<th>Time<\/th>/<th>Zeit<\/th>/g"
				mysed "s/<th>Type<\/th>/<th>Typ<\/th>/g"
				mysed "s/<th>Action<\/th>/<th>Aktion<\/th>/g"
			fi

			if [[ "$i" = */db_lists.php || "$i" = */db_graph.php || "$i" = */db_queries.php ]]; then
				mysed "s/Click to select date and time range/Klicken Sie hier, um Datum und Zeitbereich auszuw\&auml;hlen/g"
				mysed "s/Date and time range:/Datums- und Zeitbereich:/g"
			fi

			if [[ "$i" = */db_lists.php || "$i" = */queries.php || "$i" = */db_queries.php || "$i" = */index.php ]]; then
				mysed "s/<th>Client<\/th>/<th>System<\/th>/g"
			fi

			if [[ "$i" = */db_lists.php || "$i" = */queries.php || "$i" = */db_queries.php || "$i" = */auditlog.php || "$i" = */index.php ]]; then
				mysed "s/<th>Domain<\/th>/<th>Dom\&auml;ne<\/th>/g"
			fi

			if [[ "$i" = */db_lists.php || "$i" = */index.php ]]; then
				mysed "s/<th>Frequency<\/th>/<th>Frequenz<\/th>/g"
			fi

			if [[ "$i" = */db_lists.php || "$i" = */index.php ]]; then
				mysed "s/<th>Requests<\/th>/<th>Anfragen<\/th>/g"
				mysed "s/Top Blocked Domains/Top blockierte Dom\&auml;nen/g"
			fi

			if [[ "$i" = */audit.log || "$i" = */auditlog.php ]]; then
				mysed "s/<th>Actions<\/th>/<th>Aktionen<\/th>/g"
			fi

			if [[ "$i" = */db_lists.php || "$i" = */auditlog.php || "$i" = */index.php ]]; then
				# Tabellen \&uuml;berschriften
				mysed "s/<th>Hits<\/th>/<th>Treffer<\/th>/g"
			fi

			if [[ "$i" = */scripts/pi-hole/js/db_queries.js ]]; then
				mysed 's/$("h3#ads_percentage_today").text(parseFloat(percent).toFixed(1).toLocaleString()+" %");/$("h3#ads_percentage_today").text(formatNumber(parseFloat(percent).toFixed(1).toLocaleString()+" %"));/g'
			fi

			if [[ "$i" = */scripts/pi-hole/js/queries.js || "$i" = */scripts/pi-hole/js/db_queries.js ]]; then
				mysed "s/(cached)/(zw.gespeichert)/g"
			fi

			if [[ "$i" = */db_queries.php ]]; then
				mysed "s/>Blocked (blacklist)</>Blockiert (Schwarze Liste)</g"
				mysed "s/Blocked (regex\/wildcard)/Gesperrt (regul\&auml;rer Ausdruck \/ Platzhalter)/g"
				mysed "s/Blocked (external)/Gesperrt (extern)/g"
			fi
			#set +x

			if [[ "$i" = */scripts/pi-hole/js/db_queries.js || "$i" = */scripts/pi-hole/js/db_graph.js || "$i" = */scripts/pi-hole/js/db_lists.js ]]; then
				mysed 's/"Today"/"Heute"/g'
				mysed 's/"Yesterday"/"Gestern"/g'
				mysed 's/"Last 7 Days"/"Letzte 7 Tage"/g'
				mysed 's/"Last 30 Days"/"Letzte 30 Tage"/g'
				mysed 's/"This Month"/"Diesen Monat"/g'
				mysed 's/"Last Month"/"Letzten Monat"/g'
				mysed 's/"This Year"/"Dieses Jahr"/g'
				mysed 's/"All Time"/"Alle Zeiten"/g'

			#	mysed 's/"Custom Range"/"Benutzerdef. Bereich"/g'
				
				mysed 's/"MMMM Do YYYY,/"D. MMMM YYYY,/g'
				
				mysed 's/$(this).val(picker.startDate.format(dateformat) + " to " + picker.endDate.format(dateformat));/$(this).val(picker.startDate.format(dateformat) + " bis " + picker.endDate.format(dateformat));/g'

			fi
			
			if [[ "$i" = */scripts/pi-hole/js/db_graph.js ]]; then
				mysed 's/var date = time.getFullYear()+"-"+padNumber(time.getMonth()+1)+"-"+padNumber(time.getDate());/var date = padNumber(time.getDate())+"."+padNumber(time.getMonth()+1)+"."+time.getFullYear();/g'
				mysed 's/"Queries from "+from+" to "+to+" on "+date;/"Abfragen von "+from+" bis "+to+" am "+date;/g'
				mysed 's/(" + percentage.toFixed(1) + "%)"/(" + formatNumber(percentage.toFixed(1) + "%)")/g'
			fi

			# ==============================================================
			# Neuen Inhalt abspeichern in Datei
			if [[ ! "$itext" == "$itextOrig" ]]; then
				echo "$itext" > "$i"
			fi
		fi
	fi
}

flt="$1"

cd /var/www/html

if [ ! -e admin ]; then
	echo "PI-Hole ist nicht im Pfad /var/www/html/admin installiert worden."
	exit
fi
if [ ! -e admin_orig ]; then
	mkdir admin_orig
	cp -ra admin/* admin_orig
fi

if [ -z "$flt" ]; then
	cp -a admin_orig/* admin/

	cd /var/www/html/admin
	if [ ! -e germanFiles ]; then
		mkdir germanFiles
	fi
	cp -a $SCRIPTPATH/germanFiles/* germanFiles
fi

fl=($(find /var/www/html/admin -type d -name '.*' -prune -false -o -type f -not -name '.*' )) # | egrep -i '?[\.php|\.js]$' ))
for i in "${fl[@]}"
do
	if [ -z "$flt" ]; then
		OK=1
	else
		if [[ "$i" = *$flt* ]]; then
			OK=1
		else
			OK=0
		fi
	fi
	if [ $OK = 1 ]; then
		js=`echo "$i" | egrep -i '\.js$'`
		php=`echo "$i" | egrep -i '\.php$'`
		css=`echo "$i" | egrep -i '\.css$'`
		if [ ! -z "$js" ] || [ ! -z "$php" ] || [ ! -z "$css" ]; then
			# echo "Datei: $i"
			replaceValuesInFile "$i"
		fi
	fi
done
exit


