#!/bin/bash

replaceValuesInFile () {
	i=$1
	echo "Datei: $i"
	if [ -f "$i" ]; then
		#set -x

		if [[ "$i" = *jquery.dataTables.min.js* ]]; then
			sed -i "s/\"Showing 0 to 0 of 0 entries\"/\"Zeige 0 bis 0 von 0 Eintr\&auml;gen\"/g" "$i"
			sed -i "s/\"(filtered from _MAX_ total entries)\"/\"(gefiltert aus _MAX_ Gesamteintr\&auml;gen)\"/g" "$i"
			sed -i "s/\"Show _MENU_ entries\"/\"Zeige _MENU_ Eintr\&auml;ge\"/g" "$i"
			sed -i "s/\"No matching records found\"/\"Keine \&uuml;bereinstimmende Eintr\&auml;ge gefunden\"/g" "$i"
		fi

		if [[ "$i" = *queries.js* ]]; then
			sed -i "s/\"Blocked (gravity)\"/\"Gesperrt (Gravity)\"/g" "$i"
			sed -i "s/>(forwarded)\"/>(weitergel.)\"/g" "$i"
			sed -i "s/\"Blocked </\"Gesperrt </g" "$i"
			sed -i "s/>(external,\"/>(extern,\"/g" "$i"
			sed -i "s/\"Unknown (/\"Unbekannt (/g" "$i"

			sed -i "s/\"The server took too long to send the data.\"/\"Der Server hat zu lange gebraucht, um die Daten zu senden.\"/g" "$i"
			sed -i "s/\"An error occured while loading the data: Connection refused. Is FTL running?\"/\"Beim Laden der Daten ist ein Fehler aufgetreten: Verbindung abgelehnt. L\&auml;uft der FTL Dienst?\"/g" "$i"
			sed -i "s/\"An unknown error occured while loading the data./\"Beim Laden der Daten ist ein unbekannter Fehler aufgetreten./g" "$i"
			sed -i "s/>SECURE</>SICHER</g" "$i"
			sed -i "s/>INSECURE</>UNSICHER</g" "$i"
			sed -i "s/>BOGUS</>SCHEIN</g" "$i"
			sed -i "s/>ABADONED</>VERLASSEN</g" "$i"
			sed -i "s/>UNKNOWN</>UNBEKANNT</g" "$i"

			sed -i "s/\"Click to show only \"+this.innerHTML+\" queries\"/\"Klicken Sie hier, um nur \"+this.innerHTML+\"-Abfragen anzuzeigen\"/g" "$i"
			sed -i "s/\"Click to show only queries with domain \"+this.innerHTML/\"Klicken Sie hier, um nur Abfragen mit der Domain \"+this.innerHTML+\" anzuzeigen\"/g" "$i"
			sed -i "s/\"Click to show only queries made by \"+this.innerHTML/\"Klicken Sie hier, um nur Abfragen von \"+this.innerHTML+\" anzuzeigen\"/g" "$i"
			
		fi

		if [[ "$i" = *jquery.dataTables.min.js* ]]; then
			sed -i "s/\"Processing...\"/\"wird bearbeitet...\"/g" "$i"
			sed -i "s/\"Loading...\"/\"wird geladen...\"/g" "$i"
		fi

		if [[ "$i" = *settings.php* ]]; then
			sed -i "s/>Blocklists</>Sperrlisten</g" "$i"
			sed -i "s/>API \/ Web interface</>API \/ Web Schnittstellen</g" "$i"
			sed -i "s/>Privacy</>Privatsph\&auml;re</g" "$i"
		fi

		if [[ "$i" = *settings.php* ]]; then
			sed -i "s/>Network Information</>Netzwerk Information</g" "$i"
			sed -i "s/>Pi-hole Ethernet Interface:</>Pi-hole Ethernet Schnittstelle:</g" "$i"
			sed -i "s/>Pi-hole IPv4 address:</>Pi-hole IPv4 Adresse:</g" "$i"
			sed -i "s/>Pi-hole IPv6 address:</>Pi-hole IPv6 Adresse:</g" "$i"
			sed -i "s/>Pi-hole hostname:</>Pi-hole Hostname:</g" "$i"

			sed -i "s/>FTL version:</>FTL Version:</g" "$i"
			sed -i "s/>Process identifier (PID):</>Prozesskennung (PID):</g" "$i"
			sed -i "s/>Time FTL started:</>Startzeit FTL:</g" "$i"
			sed -i "s/>User \/ Group:</>Benutzer \/ Gruppe:</g" "$i"
			sed -i "s/>Total CPU utilization:</>Gesamt CPU-Auslastung:</g" "$i"
			sed -i "s/>Memory utilization:</Speicherauslastung:/g" "$i"
			sed -i "s/>Used memory:</>Verwendeter Speicher:</g" "$i"
			sed -i "s/>DNS cache size:</>DNS-Cache-Gr\&ouml;\&szlig;e:</g" "$i"
			sed -i "s/>DNS cache insertions:</>DNS-Cache-Einf\&uuml;gungen:</g" "$i"
			sed -i "s/>DNS cache evictions:</>DNS-Cache-R\&auml;umungen:</g" "$i"

			sed -i "s/>The FTL service is offline!</>Der FTL-Dienst ist offline!</g" "$i"
			sed -i "s/See also our </Siehe auch unsere </g" "$i"
			sed -i "s/>Danger Zone!</>Gefahrenzone!</g" "$i"

			sed -i "s/>Disable query logging</>Abfrageprotokollierung deaktivieren</g" "$i"
			sed -i "s/>Disable query logging and flush logs</>Abfrageprotokollierung deaktivieren und Protokoll-Eintr\&auml;ge l\&ouml;schen</g" "$i"
			sed -i "s/>Restart DNS resolver</>DNS-Aufl\&ouml;sung neu starten</g" "$i"
			sed -i "s/>Flush logs</>Protolleintr\&auml;ge l\&ouml;schen</g" "$i"
			sed -i "s/>Power off System</>System ausschalten</g" "$i"
			sed -i "s/>Restart system</>System neustarten</g" "$i"


			sed -i "s/\"There was a problem applying your settings.<br>Debugging information:<br>PHP error /\"Beim Anwenden Ihrer Einstellungen ist ein Problem aufgetreten.<br>Debugging-Informationen:<br>PHP Fehler /g" "$i"
			sed -i "s/\"unknown\"/\"unbekannt\"/g" "$i"
			sed -i "s/>Blocklists used to generate Pi-hole's Gravity: </>Sperrlisten nutzen zur erzeugung Pi-hole's Gravit\&auml;t</g" "$i"
			sed -i "s/\"Enter one URL per line to add new blocklists\"/\"Geben Sie eine URL pro Zeile ein, um neue Sperrlisten hinzuzuf\&uuml;gen\"/g" "$i"
			sed -i "s/>Save</>Speichern</g" "$i"
			sed -i "s/>Save and Update when you're done!</>Speichern und aktualisieren, sobald Sie fertig sind!</g" "$i"
			sed -i "s/>Save and Update</>Speeicern und aktualisieren</g" "$i"
			sed -i "s/>Make sure your router's DHCP server is disabled when using the Pi-hole DHCP server!</>Stellen Sie sicher, dass das DHCP-Server Ihres Routers deaktiviert ist, wenn Sie den Pi-Hole-dHCP-Server verwenden!</g" "$i"
			sed -i "s/>Range of IP addresses to hand out</>Bereich der zu verteilenden IP-Adressen</g" "$i"
			sed -i "s/\?>disabled<\?/\?>abgeschaltet<\?/g" "$i"
			sed -i "s/>Router (gateway) IP address</>Router (Gateway) IP Adresse</g" "$i"
			sed -i "s/>Advanced DHCP settings</>Erweiterte DHCP Einstellungen</g" "$i"
			sed -i "s/>Pi-hole domain name</>Pi-Hole Domain-Name</g" "$i"
			sed -i "s/>DHCP lease time</>DHCP-Miet-Zeit</g" "$i"
                        sed -i "s/>Hint: 0 = infinite, 24 = one day, 168 = one week, 744 = one month, 8760 = one year</>Hinweis: 0 = unendlich, 24 = ein Tag, 168 = eine Woche, 744 = ein Monat, 8760 = ein Jahr</g" "$i"
                        sed -i "s/>Enable IPv6 support (SLAAC + RA)</>IPv6-Unterst\&uuml;tzung (SLAAC + RA) aktivieren</g" "$i"
                        sed -i "s/>Enable DHCP rapid commit (fast address assignment)</>Schnelles Festschreiben von DHCP (schnelle Adresszuweisung)  aktivieren</g" "$i"
                        sed -i "s/>DHCP leases<>DHCP-Mieten<//g" "$i"
                        sed -i "s/>Currently active DHCP leases</>Derzeit aktive DHCP-Mieten</g" "$i"
                        sed -i "s/>MAC address</>MAC Adresse</g" "$i"
                        sed -i "s/>IP address</>IP Adresse</g" "$i"
                        sed -i "s/\"Lease type: IPv</\"Lease-Typ IPv</g" "$i"
                        sed -i "s/>Remaining lease time: </>Verbleibende Mietzeit: </g" "$i"
                        sed -i "s/>Static DHCP leases configuration</>Statische DHCP-Miet-Einstellung</g" "$i"

                        sed -i "s/>Specifying the MAC address is mandatory and only one entry per MAC/>Die Angabe der MAC-Adresse ist obligatorisch und nur ein Eintrag pro MAC-/g" "$i"
                        sed -i "s/address is allowed. If the IP address is omitted and a host name is/Adresse ist zul\&auml;ssig. Wenn die IP-Adresse weggelassen und ein Hostname/g" "$i"
                        sed -i "s/given, the IP address will still be generated dynamically and the/angegeben wird, wird die IP-Adresse weiterhin dynamisch generiert und der/g" "$i"
                        sed -i "s/specified host name will be used. If the host name is omitted, only/angegebene Hostname verwendet. Wenn der Hostname weggelassen wird, dann/g" "$i"
                        sed -i "s/a static lease will be added.</wird nur eine statische Miete hinzugef\&uuml;gt.</g" "$i"

                        sed -i "s/>Upstream DNS Servers</>>Upstream DNS-Server<</g" "$i"
                        sed -i "s/> disabled </> abgschaltet </g" "$i"
                        sed -i "s/>ECS (Extended Client Subnet) defines a mechanism for recursive resolvers to send partial client IP address information to authoritative DNS name servers. Content Delivery Networks (CDNs) and latency-sensitive services use this to give geo-located responses when responding to name lookups coming through public DNS resolvers. <em>Note that ECS may result in reduced privacy.</>ECS (Extended Client Subnet) definiert einen Mechanismus für rekursive Resolver, um teilweise IP-Adressinformationen des Clients an autorisierende DNS-Nameserver zu senden. Content Delivery Networks (CDNs) und latenzempfindliche Dienste verwenden diese Option, um geografische Antworten auf Namenssuchen zu geben, die \&uuml;ber \&ouml;ffentliche DNS-Resolver eingehen.<em>Beachten Sie, dass ECS zu einer Einschr\&auml;nkung der Privatsph\&auml;re f\&uuml;hren kann.</g" "$i"
                        sed -i "s/>Custom 1 (IPv4)</>Benutzerdef. 1 (IPv4)/g" "$i"
                        sed -i "s/>Custom 2 (IPv4)</>Benutzerdef. 2 (IPv4)/g" "$i"
                        sed -i "s/>Custom 3 (IPv4)</>Benutzerdef. 3 (IPv4)/g" "$i"
                        sed -i "s/>Custom 4 (IPv4)</>Benutzerdef. 4 (IPv4)/g" "$i"

                        sed -i "s/>Interface listening behavior</>Schnittstellen abh\&ouml;r Verhalten</g" "$i"
                        sed -i "s/>Listen on all interfaces</Alle Schnittstellen abh\&ouml;ren/g" "$i"
                        sed -i "s/>Allows only queries from devices that are at most one hop away (local devices)</>Erm\&ouml;glicht nur Abfragen von Geräten, die h\&ouml;chstens einen Sprung entfernt sind (lokale Ger\&auml;te)</g" "$i"
                        sed -i "s/>Listen only on interface </>Abh\&ouml;ren nur auf Schnittstelle </g" "$i"
                        sed -i "s/>Listen on all interfaces, permit all origins</>Alle Schnittstellen abh\&ouml;ren, alle Quellen zulassen</g" "$i"

                        sed -i "s/>Note that the last option should not be used on devices which are/>Beachten Sie, dass die letzte Option nicht für Ger\&auml;te verwendet werden/g" "$i"
                        sed -i "s/directly connected to the Internet. This option is safe if your/sollte, die direkt mit dem Internet verbunden sind. Diese Option ist/g" "$i"
                        sed -i "s/Pi-hole is located within your local network, i.e. protected behind/sicher, wenn sich Ihr Pi-Hole in Ihrem lokalen Netzwerk befindet, d. H./g" "$i"
                        sed -i "s/your router, and you have not forwarded port 53 to this device. In/Hinter Ihrem Router gesch\&uuml;tzt ist und Sie Port 53 nicht an dieses Ger\&auml;t/g" "$i"
                        sed -i "s/virtually all other cases you have to make sure that your Pi-hole is/weitergeleitet haben. In praktisch allen anderen F\&auml;llen müssen Sie sicher-/g" "$i"
                        sed -i "s/properly firewalled.</stellen, dass Ihr Pi-Hole ordnungsgem\&auml;\&szlig; durch eine Firewall gesch\&uuml;tzt ist.</g" "$i"

                        
		fi

		if [[ "$i" = *queries.php* ]]; then
			sed -i "s/\"showing\"\;/\"Anzeige\"\;/g" "$i"
			sed -i "s/\"showing permitted\"\;/\"Anzeigen erlaubt\"\;/g" "$i"
			sed -i "s/\"showing blocked\"\;/\"Anzeige blockiert\"\;/g" "$i"
			sed -i "s/\"showing no queries (due to setting)\"\;/\"Anzeige keiner Abfrage (aufgrund der Einstellungen)\"\;/g" "$i"
			sed -i "s/\"showing\"\;/\"Anzeige\"\;/g" "$i"
			sed -i "s/\" all queries within the Pi-hole log\"\;/\" aller Abfragen im Pi-Hole-Log\"\;/g" "$i"
			sed -i "s/\" queries for client \"/\" Abfragen f\&uuml;r Client \"/g" "$i"
			sed -i "s/\" queries for domain \"/\" Abfragen f\&uuml;r Dom\&auml;ne \"/g" "$i"
			sed -i "s/\" queries within specified time interval\"/\" von Abfragen innerhalb des angegebenen Zeitintervalls\"/g" "$i"
			sed -i "s/\", privacy mode enabled\"\;/\", Datenschutzmodus aktiviert\"\;/g" "$i"
			sed -i "s/\" up to 100 queries\"/\" von mehr als 100 Abfragen\"/g" "$i"
			sed -i "s/>show all</>Alle Anzeigen</g" "$i"
			sed -i "s/>Adding </>Hinzuf\&uuml;gen /g" "$i"
			sed -i "s/> to the </> zu der </g" "$i"
			sed -i "s/> successfully added to the </> Erfolgreich hinzugef\&uuml;gt zu der /g" "$i"
			sed -i "s/>Refresh Data</>Daten aktualisieren</g" "$i"
			sed -i "s/>Timeout or Network Connection Error!</>Timeout oder Netzwerkverbindungsfehler!</g" "$i"
			sed -i "s/>Recent Queries </>Letzte Abfragen </g" "$i"
			sed -i "s/>\&nbsp\;Apply filtering on click on Type, Domain, and Clients</>\&nbsp\;Wenden Sie die Filterung an, indem Sie auf Typ, Dom\&auml;ne und Clients klicken</g" "$i"
		fi


		if [[ "$i" = *gravity.php* ]]; then
			sed -i "s/\"Blocking list updated %a days, %H:%I ago\"/\"Sperrliste aktualisiert vor %a Tagen, %H:%I\"/g" "$i"
			sed -i "s/\"Blocking list updated one day, %H:%I ago\"/\"Sperrliste aktualisiert vor einem Tag, %H:%I\"/g" "$i"
			sed -i "s/\"Blocking list updated %H:%I ago\"/\"Sperrliste aktualisiert vor %H:%I\"/g" "$i"
			sed -i "s/\"Blocking list not found\"/\"Sperrliste nicht gefunden\"/g" "$i"
			
		fi

		if [[ "$i" = *index.php* ]]; then
			sed -i "s/\"only A + AAAA queries\"/\"Nur A + AAAA Abfragen\"/g" "$i"
		fi

		if [[ "$i" = *index.js* ]]; then
			sed -i "s/\"only A + AAAA queries (\"/\"Nur A + AAAA-Abfragen (insgesamt \"/g" "$i"
			sed -i "s/\" in total)\"/\")\"/g" "$i"
			sed -i "s/\" to \"/\" nach \"/g" "$i"
			sed -i "s/\"Upstreams from \"/\"Upstreams von \"/g" "$i"
			sed -i "s/\"Forward destinations from \"/\"Ziele weiterleiten von \"/g" "$i"
			sed -i "s/\"Client activity from \"/\"Client Aktivit\&auml;t von \"/g" "$i"
			sed -i "s/\"A: IPv4 queries\"/\"A: IPv4 Abfragen\"/g" "$i"
			sed -i "s/\"AAAA: IPv6 queries\"/\"AAAA: IPv6 Abfragen\"/g" "$i"
			sed -i "s/\"Query types from \"/\"Abfragetypren von \"/g" "$i"
			sed -i "s/\"Query types\"/\"Abfrage Typen\"/g" "$i"
			sed -i "s/\"Forward destinations\"/\"Ziele weiterleiten\"/g" "$i"
		fi


		# Footer und Header
		sed -i "s/>(Update available\!)</>(Aktualisierung verf\&uuml;gbar\!)>/g" "$i"

		sed -i "s/Clients (over time)/Systeme (im Laufe der Zeit)/g" "$i"

		# Anmelde-Infos
		sed -i "s/>Logout</>Abmelden</g" "$i"
		sed -i "s/>Login</>Anmelden</g" "$i"
		sed -i "s/>Session is valid for </>Sitzung ist g\&uuml;ltig f\&uuml;r </g" "$i"
		sed -i "s/>Sign in to start your session</>Melden Sie sich an, um Ihre Sitzung zu starten</g" "$i"
		sed -i "s/placeholder=\"Password\"/placeholder=\"Passwort\"/g" "$i"
		sed -i "s/> \&rarr; Log in and go to requested page (/> \&rarr; Loggen Sie sich ein und gehen Sie zur gewünschten Seite (/g" "$i"
		sed -i "s/>Ctrl+Return</>Strg+Return</g" "$i"
		sed -i "s/> \&rarr; Log in and go to Settings page</> \&rarr; Loggen Sie sich ein und gehen Sie zur Einstellung-Seite</g" "$i"
		sed -i "s/>Forgot password</>Passwort vergessen</g" "$i"

		sed -i "s/>Verify that cookies are allowed for </>Stellen Sie sicher, dass Cookies zul\&auml;ssig sind f\&uuml;r </g" "$i"
		sed -i "s/> Wrong password!</> Falsches Passwort!/g" "$i" 

		sed -i "s/>Remember me for 7 days</>Erinnere dich an mich für 7 Tage</g" "$i"
		sed -i "s/>\&nbsp;\&nbsp;\&nbsp;Log in</>\&nbsp;\&nbsp;\&nbsp;Einloggen</g" "$i"

		sed -i "s/After installing Pi-hole for the first time, a password is generated and displayed to the user. The/Nach der erstmaligen Installation von Pi-hole wird ein Passwort generiert und dem Benutzer angezeigt. Das/g" "$i"
		sed -i "s/password cannot be retrieved later on, but it is possible to set a new password (or explicitly disable/Passwort kann später nicht mehr abgerufen werden, aber es ist möglich, ein neues Passwort festzulegen (oder/g" "$i"
		sed -i "s/the password by setting an empty password) using the command/das Passwort explizit zu deaktivieren, indem Sie ein leeres Passwort festlegen), indem Sie den Befehl verwenden:/g" "$i"


		# Systemaktivitäten
		sed -i "s/Memory usage:/Speichernutzung:/g" "$i"
		sed -i "s/<\/i> Load:/<\/i> Auslst.:/g" "$i"
		sed -i "s/i> Active/i> Aktiv/g" "$i"
		
		# Menu
		sed -i "s/class=\"header\">MAIN NAVIGATION<\/li>/class=\"header\">HAUPTNAVIGATION<\/li>/g" "$i"
		sed -i "s/<span>Dashboard<\/span>/<span>Übersicht<\/span>/g" "$i"
		sed -i "s/>Query Log</>Abfragen Protokoll</g" "$i"
		sed -i "s/>Long term data</>Langzeitdaten</g" "$i"

		sed -i "s/>Graphics</>Grafiken</g" "$i"
		sed -i "s/>Top Lists</>Top Listen</g" "$i"
		sed -i "s/Top Clients (total)/Top Clients (Gesamt)/g" "$i"
		sed -i "s/Top Clients (blocked only)/Top Clients (nur blockierte)/g" "$i"

		sed -i "s/>Whitelist</>Weiße Liste</g" "$i"
		sed -i "s/>Blacklist</>Schwarze Liste</g" "$i"

		sed -i "s/>Disable\&nbsp;\&nbsp;\&nbsp;</>Abschalten\&nbsp;\&nbsp;\&nbsp;</g" "$i"
		sed -i "s/>Disable</>Abschalten</g" "$i"
		sed -i "s/\"Disable/\"Abschalten/g" "$i"

		sed -i "s/>Enable\&nbsp;\&nbsp;\&nbsp;</>Einschalten\&nbsp;\&nbsp;\&nbsp;</g" "$i"
		sed -i "s/ena.text(\"Enable\")/ena.text(\"Anschalten\")/g" "$i"
		sed -i "s/\"Enable (/\"Anschalten (/g" "$i"
		sed -i "s/>Enable</>Einschalten</g" "$i"

		sed -i "s/>Permanently</>Permanent</g" "$i"
		sed -i "s/>For 10 seconds</>Für 10 Sekunden</g" "$i"
		sed -i "s/>For 30 seconds</>Für 30 Sekunden</g" "$i"
		sed -i "s/>For 5 minutes</>Für 5 Minuten</g" "$i"
		sed -i "s/>Custom time</>Benutzerdefinierte Zeit</g" "$i"
		sed -i "s/>Network</>Netzwerk</g" "$i"

		sed -i "s/>Tools</>Werkzeuge</g" "$i"
		sed -i "s/>Update Gravity</>Aktualisierung Gravity</g" "$i"
		sed -i "s/>Query List</>Abfragelisten</g" "$i"
		sed -i "s/>Audit log</>Prüfprotokoll</g" "$i"
		sed -i "s/>Tail pihole.log</>pihole.log anzeigen</g" "$i"
		sed -i "s/>Tail pihole-FTL.log</>pihole-FTL.log anzeigen</g" "$i"
		sed -i "s/>Generate debug log</>Erstelle debug-Ablaufverfolgungsdatei</g" "$i"
		sed -i "s/>Settings</>Einstellungen</g" "$i"
		sed -i "s/>Donate</>Spenden</g" "$i"
		sed -i "s/>Help</>Hilfe</g" "$i"


		# Diese Ersetzungen dürfen nicht ausgeführt werden, da hier auch interne Werte geändert werden.
		# Nach den Ersetzungen funktioniert die Webseite nicht mehr wie gewünscht.
		#sed -i "s/""Search:""/""Suche:""/g" "$i"
		#sed -i "s/""No matching records found""/""keine &uuml;bereinstimmungen gefunden""/g" "$i"
		#sed -i "s/""Processing...""/""wird bearbeitet...""/g" "$i"
		#sed -i "s/""Loading...""/""wird geladen...""/g" "$i"
		#sed -i "s/""Showing 0 to 0 of 0 entries""/""Zeige 0 bis 0 von 0 Einträgen""/g" "$i"
		#sed -i "s/""(filtered from _MAX_ total entries)""/""(gefiltert von _MAX_ Gesamteinträgen)""/g" "$i"

		# Anzeige Werte
		# Nach der Veränderung werden keine Werte bei der Protokoll-Ausgabe angezeigt
		#sed -i "s/sThousands:"",""/sThousands:"".""/g" "$i"
		#sed -i "s/sDecimal:""""/sDecimal:"",""/g" "$i"

		# Tabellen überschriften
		sed -i "s/<th>Hits<\/th>/<th>Treffer<\/th>/g" "$i"
		sed -i "s/<th>Domain<\/th>/<th>Domäne<\/th>/g" "$i"
		sed -i "s/<th>Frequency<\/th>/<th>Frequenz<\/th>/g" "$i"

		sed -i "s/<th>Requests<\/th>/<th>Anfragen<\/th>/g" "$i"
		sed -i "s/<th>Client<\/th>/<th>System<\/th>/g" "$i"
		sed -i "s/<th>Actions<\/th>/<th>Aktionen<\/th>/g" "$i"


		sed -i "s/<th>Time<\/th>/<th>Zeit<\/th>/g" "$i"
		sed -i "s/<th>Type<\/th>/<th>Typ<\/th>/g" "$i"
		sed -i "s/<th>Reply<\/th>/<th>Antwort<\/th>/g" "$i"
		sed -i "s/<th>Action<\/th>/<th>Aktion<\/th>/g" "$i"
		sed -i "s/>Blacklist</>Schwarze Liste</g" "$i"
		sed -i "s/>Whitelist</>Wei\&szlig;e Liste</g" "$i"

		sed -i "s/(forwarded)</(weitergel.)</g" "$i"
		sed -i "s/(cached)/(zw.gespeichert)/g" "$i"
		sed -i "s/>Blocked (blacklist)</>Blockiert (Blacklist)</g" "$i"

		# Anderes
		# sed -i "s/Total queries/Abfragen insgesamt/g" "$i"
		sed -i "s/Total queries (<span id=\"unique_clients\">-<\/span> clients/Abfragen insgesamt (<span id=\"unique_clients\">-<\/span> Systeme/g" "$i"
		sed -i "s/\> clients)/\> Systeme)/g" "$i"
		sed -i "s/Queries Blocked/Abfragen blockiert/g" "$i"
		sed -i "s/Percent Blocked/Prozentual blockiert/g" "$i"
		sed -i "s/Domains on Blocklist/Domains in Blockliste/g" "$i"

		# sed -i "s/Upstreams from/Upstreams von/g" "$i"
		sed -i "s/Upstreams from \"+from+\" to /Upstreams von \"+from+\" nach /g" "$i"
		sed -i "s/Total DNS Queries/Gesamte DNS-Abfragen/g" "$i"
		sed -i "s/Blocked DNS Queries/Blockierte DNS Abfragen/g" "$i"

		sed -i "s/Client activity from \"+from+\" to /System Aktivitäten von \"+from+\" nach /g" "$i"

		sed -i "s/Query Types/Abfragetypen/g" "$i"
		sed -i "s/Query types/Abfragetypen/g" "$i"

		sed -i "s/Queries answered by/Anfragen beantwortet von/g" "$i"
		sed -i "s/Forward destinations/Ziele weitergeleitet/g" "$i"
		sed -i "s/Top Permitted Domains/Top zulässige Domänen/g" "$i"
		sed -i "s/Top Blocked Domains/Top blockierte Domänen/g" "$i"

		sed -i "s/Queries over last <?php echo getinterval(); ?> hours/Abfragen der letzten <?php echo getinterval(); ?> Stunden/g" "$i"
		sed -i "s/Blocklists used to generate Pi-hole\'s Gravity/Blocklisten zur Erzeugung Pi-hole\'s Gravity/g" "$i"

		sed -i "s/>checked</>gesetzt</g" "$i"

		sed -i "s/>Blocked queries</>Blockierte Abfragen</g" "$i"
		sed -i "s/>Allowed queries</>Erlaubte Abfragen</g" "$i"

		# Buttons
		sed -i "s/> Audit</> Prüfung</g" "$i"
		sed -i "s/> Whitelist</> Weiße L.</g" "$i"
		sed -i "s/> Blacklist</> Schw. L.</g" "$i"

		sed -i "s/>Audit log (showing live data)</>Prüfungprotokoll (Anzeige Echtdaten)</g" "$i"
		sed -i "s/><strong>Important:<\/strong> Note that black- and whitelisted domains are not automatically applied on this page to avoid restarting the DNS service too often. Instead, click on this button, to have the new settings become effective:</><strong>Wichtig:<\/strong> Beachten Sie, dass Schwarz- und Weiße-Listen-Domains auf dieser Seite nicht automatisch angewendet werden, um einen zu häufigen Neustart des DNS-Diensts zu vermeiden. Klicken Sie stattdessen auf diese Schaltfläche, damit die neuen Einstellungen wirksam werden:</g" "$i"
		sed -i "s/>Update black-\/whitelists</>Aktualisiere Schwarz-\/Weiß-Listen</g" "$i"

		sed -i "s/>Compute graphical statistics from the Pi-hole query database</>Grafische Statistiken aus der PiHole-Abfragen-Datenbank</g" "$i"

		sed -i "s/\"Add a domain (example.com or sub.example.com)\"/\"Hinzufügen einer Domäne (z.B. beispiel.de oder www.beispiel.de)\"/g" "$i"
		sed -i "s/echo \"Blacklist\"/echo \"Schwarze Liste\"/g" "$i"
		sed -i "s/echo \"Whitelist\"/echo \"Weiße Liste\"/g" "$i"
		sed -i "s/>Exact blocking</>Genaues Blockieren</g" "$i"
		sed -i "s/>Add (exact)</>Hinzufügen (genau)</g" "$i"
		sed -i "s/>Add (wildcard)</>Hinzufügen (Platzhalter)</g" "$i"
		sed -i "s/>Add (regex)</>Hinzufügen (reg. Ausdr.)</g" "$i"

		# Ersetzung fehlerhaft:
		#sed -i "s/>Regex<\/a> &amp; Wildcard blocking</>Reg. Ausdr.<\/a> &amp; Platzhalter blockieren</g" "$i"

		sed -i "s/> Donate<\/a><\/strong> if you found this useful.</> Spende<\/a><\/strong> wenn Du dieses nützlich findest.</g" "$i"
		sed -i "s/>Web Interface Version </>Web Schnittstellen Version </g" "$i"


		sed -i "s/Depending on how large of a range you specified, the request may time out while Pi-hole tries to retrieve all the data./Je nachdem, wie gro\&szlig; der von Ihnen angegebene Bereich ist, tritt m\&ouml;glicherweise eine Zeit\&uuml;berschreitung auf, w\&auml;hrend Pi-hole versucht, alle Daten abzurufen./g" "$1"
		sed -i "s/Queries over the selected time period/Abfragen über den ausgewählten Zeitraum/g" "$i"
		sed -i "s/Specify date range to be queried from the Pi-hole query database/Geben Sie den Datumsbereich an, der aus der Pi-Hole-Abfragedatenbank abgefragt werden soll/g" "$i"

		sed -i "s/Click to select date and time range/Klicken Sie hier, um Datum und Zeitbereich auszuw\&auml;hlen/g" "$i"

		sed -i "s/Date and time range:/Datums- und Zeitbereich:/g" "$i"
		sed -i "s/Query status:/Abfrage-Status:/g" "$i"
		sed -i "s/Recent Queries/Letzte Abfragen/g" "$i"
		sed -i "s/Queries Total/Abfragen insgesamt/g" "$i"
		sed -i "s/Blocked (exact)/Gesperrt (genau)/g" "$i"
		sed -i "s/Blocked (regex\/wildcard)/Gesperrt (regul\&auml;rer Ausdruck \/ Platzhalter)/g" "$i"

		sed -i "s/Blockiert (Blacklist)/Blockiert (Schwarze Liste)/g" "$i"
		sed -i "s/Blocked (external)/Gesperrt (extern)/g" "$i"
		#set +x
	fi
}

flt="$1"

cd /var/www/html

if [ ! -e admin ]; then
	mkdir admin
fi

cd /var/www/html

if [ -z "$flt" ]; then
	cp -a admin_orig/* admin/

	cd /var/www/html/admin
fi

fl=($(find /var/www/html/admin -type d -name '.*' -prune -false -o -type f -not -name '.*' )) # | egrep -i '?[\.php|\.js]$' ))
for i in "${fl[@]}"
do
	if [ -z "$flt" ]; then
		OK=1
	else
		if [[ "$i" = *$flt* ]]; then
			OK=1
		else
			OK=0
		fi
	fi
	if [ $OK = 1 ]; then
		js=`echo "$i" | egrep -i '\.js$'`
		php=`echo "$i" | egrep -i '\.php$'`
		css=`echo "$i" | egrep -i '\.css$'`
		if [ ! -z "$js" ] || [ ! -z "$php" ] || [ ! -z "$css" ]; then
	        # echo "Datei: $i"
			replaceValuesInFile "$i"
		fi
	fi
done
exit


